### ISSUE TITLE
qtimgui submodule doesn't point to qtimgui

### ISSUE THREAD

**Issue by begleysm** [berkbavas/Earth#1]
Your project requires `qtimgui` (in the Dependencies directory) but it doesn't actually point at `qtimgui`.  I was able to find and grab https://github.com/seanchas116/qtimgui myself but you might want to fix this so that your project can be cloned in its entirety with `git clone --recurse-submodules https://github.com/berkbavas/Earth.git`.

**Comment by berkbavas** [comment]
Opps. Thanks for pointing the issue.
