### ISSUE TITLE
SegFault when running

### ISSUE THREAD

**Issue by begleysm** [berkbavas/Earth#2]
I've cloned your repo and cloned `qtimgui` w/ `recurse-submodules`.  I've got it building in under Qt 6.4 in Qt Creator 8.0.2 (though I'm currently compiling with MinGW 11.2.0 64-bit instead of MSVC2019 (I've downloaded MSVC2019 but haven't yet figured out how to get Qt Creator to recognize it).  I've also copied the Resources folder to where the EXE resides.  However, I'm getting a SegFault at [`ModelData.cpp:36`](https://github.com/berkbavas/Earth/blob/42e2404741a80aa636061db4154e564e57c20c55/ModelData.cpp#L36) when `mVAO.bind()` is called.  Any thoughts?

![image](https://user-images.githubusercontent.com/1275999/199771912-32fbee20-ffca-4e87-a003-3d64c32dd658.png)

**Comment by berkbavas** [comment]
Could you please set the folder where exe resides as the working directory?

For example mine is **C:\Users\berkb\Desktop\build-Earth-Desktop_Qt_6_3_0_MSVC2019_64bit-Release\release**

**Comment by berkbavas** [comment]
Or you can use post build script. Just add a custom build step. Settings are as follows:
![image](https://user-images.githubusercontent.com/53399385/199775036-9bb571a8-fd94-4da5-ba9c-505e4827c137.png)

**Comment by begleysm** [comment]
That fixed it thank you!
