### ISSUE TITLE
notfound imgui.h

### ISSUE THREAD

**Issue by RichardsATcn** [berkbavas/Earth#3]
已启动生成...
1>------ 已启动生成: 项目: Earth, 配置: Debug x64 ------
1>Automatic MOC and UIC for target Earth
1>mocs_compilation_Debug.cpp
1>E:\QtProject\gitqt\berkbavas_Earth\Include\Node.h(10,10): fatal error C1083: 无法打开包括文件: “imgui.h”: No such file or directory
1>Camera.cpp
1>E:\QtProject\gitqt\berkbavas_Earth\Include\Node.h(10,10): fatal error C1083: 无法打开包括文件: “imgui.h”: No such file or directory
1>Controller.cpp
1>E:\QtProject\gitqt\berkbavas_Earth\Include\Node.h(10,10): fatal error C1083: 无法打开包括文件: “imgui.h”: No such file or directory
1>DummyCamera.cpp
1>E:\QtProject\gitqt\berkbavas_Earth\Include\Node.h(10,10): fatal error C1083: 无法打开包括文件: “imgui.h”: No such file or directory
1>Main.cpp
1>E:\QtProject\gitqt\berkbavas_Earth\Include\Window.h(7,10): fatal error C1083: 无法打开包括文件: “imgui.h”: No such file or directory
1>Model.cpp
1>E:\QtProject\gitqt\berkbavas_Earth\Include\Node.h(10,10): fatal error C1083: 无法打开包括文件: “imgui.h”: No such file or directory
1>ModelData.cpp
1>Node.cpp
1>E:\QtProject\gitqt\berkbavas_Earth\Include\Node.h(10,10): fatal error C1083: 无法打开包括文件: “imgui.h”: No such file or directory
1>PerspectiveCamera.cpp
1>E:\QtProject\gitqt\berkbavas_Earth\Include\Node.h(10,10): fatal error C1083: 无法打开包括文件: “imgui.h”: No such file or directory
1>Shader.cpp
1>Sun.cpp
1>E:\QtProject\gitqt\berkbavas_Earth\Include\Node.h(10,10): fatal error C1083: 无法打开包括文件: “imgui.h”: No such file or directory
1>Window.cpp
1>E:\QtProject\gitqt\berkbavas_Earth\Include\Window.h(7,10): fatal error C1083: 无法打开包括文件: “imgui.h”: No such file or directory
1>qrc_Resources.cpp
1>正在生成代码...
1>已完成生成项目“Earth.vcxproj”的操作 - 失败。
2>------ 已跳过“生成”: 项目: ALL_BUILD, 配置: Debug x64 ------
2>没有为此解决方案配置选中要生成的项目 
========== 生成: 0 成功，1 失败，1 最新，1 已跳过 ==========
========= 生成 开始于 11:06 PM，并花费了 10.196 秒 ==========

**Comment by berkbavas** [comment]
I have added missing qtimgui lib. It should be fixed now.
